services:
  postgres:
    image: postgres:16
    container_name: kapture_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: kapture
      POSTGRES_USER: kapture_user
      POSTGRES_PASSWORD: kapture_password

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kapture_user -d kapture"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
