from enum import Enum


class CallState(str, Enum):
    CALL_CONNECTED = "CALL_CONNECTED"
    INTRODUCTION = "INTRODUCTION"
    CHECK_PERSON = "CHECK_PERSON"
    AUTHENTICATION = "AUTHENTICATION"
    DISCLOSE_OVERDUE = "DISCLOSE_OVERDUE"
    INTENT_HANDLING = "INTENT_HANDLING"
    DISPOSITION = "DISPOSITION"
    END = "END"