from enum import Enum


class CallDisposition(str, Enum):
    PAYMENT_INITIATED = "PAYMENT_INITIATED"
    PTP_COMMITTED = "PTP_COMMITTED"
    DISPUTE_RAISED = "DISPUTE_RAISED"
    NEGOTIATION_REQUIRED = "NEGOTIATION_REQUIRED"
    HUMAN_ESCALATION = "HUMAN_ESCALATION"
    CLARIFICATION_REQUIRED = "CLARIFICATION_REQUIRED"